services:
  server:
    build: ./src
    restart: always
    ports:
      - 8001:8001
    networks:
      - frontend
    labels:
      # web
      - "traefik.enable=true"
      - "traefik.http.routers.wallclock.entrypoints=websecure"
      - "traefik.http.routers.wallclock.rule=Host(`wallclock.farjanverse.party`) && PathPrefix(`/`)"
      - "traefik.http.routers.wallclock.tls=true"
      - "traefik.http.routers.wallclock.tls.certresolver=default"
    env_file:
      - ../.digitransit.env

networks:
  frontend:
    name: frontend
    external: true
